CREATE TABLE [dbo].[ADA100] (
    [pno]            INT             NOT NULL,
    [company]        VARCHAR (2)     NOT NULL,
    [plant]          VARCHAR (4)     NULL,
    [asset]          VARCHAR (14)    NOT NULL,
    [asset_name]     VARCHAR (500)   NULL,
    [asset_class]    VARCHAR (2)     NOT NULL,
    [install_date]   DATE            NULL,
    [install_amount] NUMERIC (15, 3) NULL,
    [install_place]  VARCHAR (500)   NULL,
    [apply_date]     DATE            NULL,
    [apply_amount]   NUMERIC (15, 3) NULL,
    [ecost]          VARCHAR (20)    NULL,
    [dept]           VARCHAR (4)     NULL,
    [using_dept]     VARCHAR (4)     NULL,
    [vendor]         VARCHAR (12)    NULL,
    [goods]          VARCHAR (12)    NULL,
    [remark]         VARCHAR (500)   NULL,
    [manager1]       VARCHAR (6)     NULL,
    [manager2]       VARCHAR (6)     NULL,
    [qty]            NUMERIC (15, 3) NULL,
    [unit]           VARCHAR (4)     NULL,
    [spec]           VARCHAR (200)   NULL,
    [control_no]     VARCHAR (40)    NULL,
    [bank]           VARCHAR (12)    NULL,
    [bank_account]   VARCHAR (40)    NULL,
    [years]          VARCHAR (4)     NULL,
    [slip_no]        VARCHAR (14)    NULL,
    [account]        VARCHAR (8)     NULL,
    [prj_id]         INT             NULL,
    [cdt]            VARCHAR (8)     NULL,
    [cid]            VARCHAR (6)     NULL,
    [mdt]            VARCHAR (8)     NULL,
    [mid]            VARCHAR (6)     NULL
);

