CREATE TABLE [dbo].[CLA390] (
    [company]         VARCHAR (2)     NOT NULL,
    [yymm]            VARCHAR (10)    NOT NULL,
    [kbn]             VARCHAR (2)     NOT NULL,
    [flock]           VARCHAR (20)    NOT NULL,
    [hh]              VARCHAR (20)    NOT NULL,
    [hr]              VARCHAR (20)    NOT NULL,
    [goods]           VARCHAR (20)    NULL,
    [account]         VARCHAR (20)    NOT NULL,
    [amt_bg]          DECIMAL (22, 3) NULL,
    [amt_growing]     DECIMAL (22, 3) NULL,
    [amt_mv_in]       DECIMAL (22, 3) NULL,
    [amt_mv_out]      DECIMAL (22, 3) NULL,
    [amt_bp_ayam]     DECIMAL (22, 3) NULL,
    [amt_bp_seleksi]  DECIMAL (22, 3) NULL,
    [amt_amo]         DECIMAL (22, 3) NULL,
    [amt_ed]          DECIMAL (22, 3) NULL,
    [amt_laying]      DECIMAL (22, 3) NULL,
    [amt_he]          DECIMAL (22, 3) NULL,
    [amt_bp_egg_farm] DECIMAL (22, 3) NULL,
    [amt_hatching]    DECIMAL (22, 3) NULL,
    [amt_bp_egg_hr]   DECIMAL (22, 3) NULL,
    [amt_prod]        DECIMAL (22, 3) NULL,
    [amt_moc]         DECIMAL (22, 3) NULL,
    [amt_doc_he]      DECIMAL (22, 3) NULL,
    [amt_etc]         DECIMAL (22, 3) NULL,
    [amt_use]         DECIMAL (22, 3) NULL,
    [pid]             BIGINT          IDENTITY (1, 1) NOT NULL
);

