CREATE TABLE [dbo].[LEA500] (
    [company]      VARCHAR (2)     NOT NULL,
    [ymd]          DATE            NOT NULL,
    [flock]        VARCHAR (20)    NOT NULL,
    [hh]           VARCHAR (10)    NOT NULL,
    [hr]           VARCHAR (10)    NOT NULL,
    [he_rcv]       DECIMAL (15, 3) NULL,
    [he_loss]      DECIMAL (15, 3) NULL,
    [he_miss]      DECIMAL (15, 3) NULL,
    [he_spot]      DECIMAL (15, 3) NULL,
    [he_thin]      DECIMAL (15, 3) NULL,
    [he_crack]     DECIMAL (15, 3) NULL,
    [he_damage]    DECIMAL (15, 3) NULL,
    [he_dirty]     DECIMAL (15, 3) NULL,
    [he_small]     DECIMAL (15, 3) NULL,
    [he_jumbo]     DECIMAL (15, 3) NULL,
    [he_aborsi]    DECIMAL (15, 3) NULL,
    [he_setting]   DECIMAL (15, 3) NULL,
    [he_in]        DECIMAL (15, 3) NULL,
    [he_out]       DECIMAL (15, 3) NULL,
    [st_setting]   DECIMAL (15, 3) NULL,
    [st_aborsi]    DECIMAL (15, 3) NULL,
    [hr_infertile] DECIMAL (15, 3) NULL,
    [hr_loss]      DECIMAL (15, 3) NULL,
    [hr_explode]   DECIMAL (15, 3) NULL,
    [hr_fertile]   DECIMAL (15, 3) NULL,
    [hr_dis]       DECIMAL (15, 3) NULL,
    [hr_hatch]     DECIMAL (15, 3) NULL,
    [hr_ompal]     DECIMAL (15, 3) NULL,
    [hr_bloat]     DECIMAL (15, 3) NULL,
    [hr_def]       DECIMAL (15, 3) NULL,
    [hr_weak]      DECIMAL (15, 3) NULL,
    [hr_dead]      DECIMAL (15, 3) NULL,
    [hr_nipple]    DECIMAL (15, 3) NULL,
    [hr_aborsi]    DECIMAL (15, 3) NULL,
    [hr_a]         DECIMAL (15, 3) NULL,
    [hr_b]         DECIMAL (15, 3) NULL,
    [hr_c]         DECIMAL (15, 3) NULL,
    [hr_a2]        DECIMAL (15, 3) NULL,
    [hr_a3]        DECIMAL (15, 3) NULL
);

