CREATE TABLE [dbo].[PDA200] (
    [pid]           INT             IDENTITY (1, 1) NOT NULL,
    [company]       VARCHAR (2)     NOT NULL,
    [keyno]         VARCHAR (20)    NULL,
    [plant]         VARCHAR (10)    NOT NULL,
    [flock]         VARCHAR (20)    NOT NULL,
    [hh]            VARCHAR (20)    NOT NULL,
    [io_date]       DATE            NOT NULL,
    [od_female]     DECIMAL (15, 3) NULL,
    [od_male]       DECIMAL (15, 3) NULL,
    [oc_female]     DECIMAL (15, 3) NULL,
    [oc_male]       DECIMAL (15, 3) NULL,
    [af_female]     DECIMAL (15, 3) NULL,
    [af_male]       DECIMAL (15, 3) NULL,
    [sl_female]     DECIMAL (15, 3) NULL,
    [sl_male]       DECIMAL (15, 3) NULL,
    [om_female]     DECIMAL (15, 3) NULL,
    [om_male]       DECIMAL (15, 3) NULL,
    [air]           DECIMAL (15, 3) NULL,
    [to_flock]      VARCHAR (20)    NOT NULL,
    [to_hh]         VARCHAR (20)    NOT NULL,
    [chick_in_date] DATE            NULL,
    [memo]          VARCHAR (200)   NULL,
    [cid]           INT             NULL,
    [cdt]           DATETIME        NULL,
    [mid]           INT             NULL,
    [mdt]           DATETIME        NULL
);

