CREATE TABLE [dbo].[PPA500] (
    [pid]             INT             IDENTITY (1, 1) NOT NULL,
    [company]         VARCHAR (2)     NOT NULL,
    [keyno]           VARCHAR (20)    NULL,
    [hr]              VARCHAR (10)    NOT NULL,
    [flock]           VARCHAR (20)    NOT NULL,
    [hh]              VARCHAR (10)    NOT NULL,
    [date_rcv]        DATE            NULL,
    [date_set]        DATE            NULL,
    [date_transfer]   DATE            NULL,
    [date_pull_chick] DATE            NULL,
    [he_rcv]          DECIMAL (22, 3) NULL,
    [he_loss]         DECIMAL (22, 3) NULL,
    [he_crack]        DECIMAL (22, 3) NULL,
    [he_jumbo]        DECIMAL (22, 3) NULL,
    [he_dirty]        DECIMAL (22, 3) NULL,
    [he_small]        DECIMAL (22, 3) NULL,
    [he_miss]         DECIMAL (22, 3) NULL,
    [he_spot]         DECIMAL (22, 3) NULL,
    [he_thin]         DECIMAL (22, 3) NULL,
    [he_damage]       DECIMAL (22, 3) NULL,
    [he_aborsi]       DECIMAL (22, 3) NULL,
    [he_setting]      DECIMAL (22, 3) NULL,
    [he_in]           DECIMAL (15, 3) NULL,
    [he_out]          DECIMAL (15, 3) NULL,
    [st_setting]      DECIMAL (22, 3) NULL,
    [st_aborsi]       DECIMAL (22, 3) NULL,
    [hr_loss]         DECIMAL (22, 3) NULL,
    [hr_infertile]    DECIMAL (22, 3) NULL,
    [hr_explode]      DECIMAL (22, 3) NULL,
    [hr_fertile]      DECIMAL (22, 3) NULL,
    [hr_dis]          DECIMAL (22, 3) NULL,
    [hr_hatch]        DECIMAL (22, 3) NULL,
    [hr_ompal]        DECIMAL (22, 3) NULL,
    [hr_bloat]        DECIMAL (22, 3) NULL,
    [hr_def]          DECIMAL (22, 3) NULL,
    [hr_weak]         DECIMAL (22, 3) NULL,
    [hr_dead]         DECIMAL (22, 3) NULL,
    [hr_nipple]       DECIMAL (22, 3) NULL,
    [hr_aborsi]       DECIMAL (22, 3) NULL,
    [hr_a]            DECIMAL (15, 3) NULL,
    [hr_a2]           DECIMAL (15, 3) NULL,
    [hr_a3]           DECIMAL (15, 3) NULL,
    [hr_b]            DECIMAL (15, 3) NULL,
    [hr_c]            DECIMAL (15, 3) NULL,
    [memo]            VARCHAR (500)   NULL,
    [cid]             INT             NULL,
    [cdt]             DATETIME        NULL,
    [mid]             INT             NULL,
    [mdt]             DATETIME        NULL,
    [date_farm]       DATE            NULL,
    [he_farm]         DECIMAL (22, 3) NULL
);

